version: '3.4'

services:
  contact.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  report.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

