version: '3.4'

services:
  contactdb:
    image: mongo
  
  reportdb:
    image: mongo
 
  contact.api:
    image: ${DOCKER_REGISTRY-}contactapi
    build:
      context: .
      dockerfile: Services/Contact/Contact.API/Dockerfile

  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: Services/Report/Report.API/Dockerfile

volumes:
  contact_mongo_data:
  report_mongo_data: