version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  contactdb:
    container_name: contactdb
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - contact_mongo_data:/data/db
  
  reportdb:
    container_name: reportdb
    restart: always
    ports: 
      - "27018:27017"
    volumes:
      - report_mongo_data:/data/db

  contact.api:
    container_name: contact.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ContactDatabase__ConnectionString=mongodb://contactdb:27017"
      - "ContactDatabase__DatabaseName=ContactDb"
      - "ContactDatabase__ContactsCollectionName=Contacts"
    depends_on:
      - contactdb
    ports:
      - "8001:80"

  report.api:
    container_name: report.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReportDatabase__ConnectionString=mongodb://reportdb:27017"
      - "ReportDatabase__DatabaseName=ReportDb"
      - "ReportDatabase__ReportsCollectionName=Reports"
    depends_on:
      - reportdb
      - rabbitmq
    ports:
      - "8002:80"

